// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esguaeuyxhdgxwycpwnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzZ3VhZXV5eGhkZ3h3eWNwd254Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzMjM3NzIsImV4cCI6MjA0OTg5OTc3Mn0.hSDdm-qj5aTFsxsYsKp-A_FykrwhPUBs5TDnMHrDoKM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);